services:
  linkpath:
    build: .
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "8080:8080"
    volumes:
      - pb_data:/app/pb_data
    environment:
      - TZ=UTC
      - APP_HTTP=0.0.0.0:8080
      - PB_HTTP=0.0.0.0:8090
    labels:
      - "traefik.enable=true"
      # Application
      - "traefik.http.routers.linkpath_app.rule=Host(`linkpa.th`)"
      - "traefik.http.routers.linkpath_app.entrypoints=websecure"
      - "traefik.http.routers.linkpath_app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.linkpath_app.service=linkpath_app"
      - "traefik.http.services.linkpath_app.loadbalancer.server.port=8080"
      # Pocketbase
      - "traefik.http.routers.linkpath_pb.rule=Host(`admin.linkpa.th`)"
      - "traefik.http.routers.linkpath_pb.entrypoints=websecure"
      - "traefik.http.routers.linkpath_pb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.linkpath_pb.service=linkpath_pb"
      - "traefik.http.services.linkpath_pb.loadbalancer.server.port=8090"

volumes:
  pb_data:
    driver: local
